### ISSUE TITLE
Unable to run, facing this issue.

### ISSUE THREAD

**Issue by lambardarr** [root-tanishq/userefuzz#6]
Traceback (most recent call last):
  File "/usr/bin/userefuzz", line 4, in <module>
    __import__('pkg_resources').run_script('userefuzz==1.1.1', 'userefuzz')
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 1460, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/userefuzz' not found in metadata at '/usr/local/lib/python3.8/dist-packages/userefuzz-1.1.1.dist-info'

**Comment by root-tanishq** [comment]
ss of the command you using

**Comment by lambardarr** [comment]
It worked thanks 😊
